spring:
  ai:

    memory:
      redis:
        host: localhost
        port: 6379
        password:
        timeout:  5000
        database: 2




#        大概率是mysql的配置
#    chat:
#      memory:
#        repository:
#          jdbc:
#            mysql:
#              jdbc-url: jdbc:mysql://localhost:3306/alibaba?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrl
#              username: root
#              password: 1314
#              driver-class-name: com.mysql.cj.jdbc.Driver
#              enabled: false

