server:
  port: 8083

spring:
  application:
    name: ai-interviewer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_interviewer?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1314

  jackson:
    date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

  # 删除这部分，这是OAuth2的配置，不是我们用的JWT
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt:
  #         jws-algorithms:

# JWT配置 - 这是自定义的配置
jwt:
  secret: AI-interviewer-secret-key-2024-this-is-a-very-long-secret-key
  expiration: 86400 # 24小时，单位：秒

mybatis-plus:
  type-aliases-package: com.lijian.**.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto