

spring:

  mail:
    host: smtp.qq.com
    port: 587
    username: 1609397402@qq.com # lijianlong144@foxmail.com
    password: wlkzmovkwrbsbadc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8


#自定义mail
email:
  from: 1609397402@qq.com  # 发件人邮箱
  fromName: AI面试系统      # 发件人名称

