
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ai_interviewer?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1314
    driver-class-name: com.mysql.cj.jdbc.Driver

    # ▼ Druid 专属配置 ▼
    druid:
      stat-view-servlet:
        enabled: true          # 开启内置监控页
        url-pattern: /druid/*  # 访问入口
        login-username: admin  # 登录用户
        login-password: admin  # 登录密码
        reset-enable: false    # 是否显示“Reset All”按钮
        allow: 127.0.0.1       # 只允许本机访问；留空则放行所有

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.css,*.png,*.jpg,*.gif,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000










#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ai_interviewer?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 1314
#    druid:
#      # 初始连接数
#      initial-size: 5
#      # 最小连接池数量
#      min-idle: 5
#      # 最大连接池数量
#      max-active: 20
#      # 获取连接时最大等待时间，单位毫秒
#      max-wait: 60000
#      # 检测连接是否有效的间隔时间，单位毫秒
#      time-between-eviction-runs-millis: 60000
#      # 连接在池中最小生存的时间，单位毫秒
#      min-evictable-idle-time-millis: 300000
#      # 连接在池中最大生存的时间，单位毫秒
#      max-evictable-idle-time-millis: 900000
#      # 用来检测连接是否有效的SQL
#      validation-query: SELECT 1
#      # 申请连接时执行validationQuery检测连接是否有效
#      test-on-borrow: false
#      # 归还连接时执行validationQuery检测连接是否有效
#      test-on-return: false
#      # 建议配置为true，不影响性能，并且保证安全性
#      test-while-idle: true
#      # 是否缓存preparedStatement，也就是PSCache
#      pool-prepared-statements: true
#      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true
#      max-pool-prepared-statement-per-connection-size: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,slf4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      # 合并多个DruidDataSource的监控数据
#      use-global-data-source-stat: true
#      # 配置DruidStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: /*
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#      # 配置DruidStatViewServlet
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        # 登录用户名和密码
#        login-username: admin
#        login-password: 123456
#        # IP白名单(没有配置或者为空，则允许所有访问)
#        allow:
#        # IP黑名单 (存在共同时，deny优先于allow)
#        deny:
#        # 是否能够重置数据
#        reset-enable: false
#        # Spring Boot 3.x需要添加以下配置
#        url-mappings: /druid/*

